#!/bin/bash

update () {
[[ ! -e "$HOME/update.sh" ]] && wget -O $HOME/update.sh https://www.dropbox.com/s/amak3tbt2l5jx86/update.sh &> /dev/null
chmod +x $HOME/update.sh
screen -dmS updateBotGen $HOME/update.sh
sleep 2
killall BotGen.sh
}
