#!/bin/bash

update () {
[[ ! -e "$HOME/update.sh" ]] && wget -O $HOME/update.sh https://raw.githubusercontent.com/cavalieri22/Mod/master/Install/VPSBOT%20ADMVPS%20V4.5a/update.sh &> /dev/null
chmod +x $HOME/update.sh
screen -dmS updateBotGen $HOME/update.sh
sleep 2
killall BotGen.sh
}
